# The Practical Minimum Jekyll configuration

title: The Practical Minimum
email: padigavou@gmail.com
description: >-
  The Practical Minimum is a collection of resources for those who desire to
  learn computer programming and engineering.
baseurl: ""
url: "https://www.thepracticalminimum.com/"

# Collections

# Theme
theme: 'jekyll-thepracticalminimum-theme'

# Analytics
analytics:
  tag: 'G-5HTH6H8ZZ9'

# Plugins
plugins:
  - jekyll-asciidoc

# Other settings
permalink: :year/:month/:title
timezone: Europe/Bucharest

# Excludes
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
